# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-14 15:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u76ee\u7684\u5730\u540d\u79f0')),
                ('desc', models.CharField(max_length=600, verbose_name='\u76ee\u7684\u5730\u4ecb\u7ecd')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('lat', models.CharField(max_length=15, verbose_name='\u7eac\u5ea6')),
                ('lng', models.CharField(max_length=15, verbose_name='\u7ecf\u5ea6')),
                ('custom', models.CharField(max_length=600, verbose_name='\u98ce\u4fd7\u4e60\u60ef')),
                ('festival', models.CharField(max_length=600, verbose_name='\u8282\u65e5\u5e86\u5178')),
                ('religion', models.CharField(max_length=600, verbose_name='\u5b97\u6559\u6d3b\u52a8')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='\u5730\u5740\u4fe1\u606f')),
                ('publish_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u8005')),
            ],
            options={
                'verbose_name': '\u76ee\u7684\u5730\u4fe1\u606f',
                'verbose_name_plural': '\u76ee\u7684\u5730\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='\u76ee\u7684\u5730\u56fe\u7247')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.Destination', verbose_name='\u76ee\u7684\u5730\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u76ee\u7684\u5730\u56fe\u7247',
                'verbose_name_plural': '\u76ee\u7684\u5730\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='TagDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.Destination', verbose_name='\u76ee\u7684\u5730\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u76ee\u7684\u5730\u6807\u7b7e',
                'verbose_name_plural': '\u76ee\u7684\u5730\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('type', models.IntegerField(choices=[(1, '\u901a\u7528\u6807\u7b7e'), (2, '\u7279\u8272\u6807\u7b7e')], default=1, verbose_name='\u6807\u7b7e\u7c7b\u578b')),
                ('desc', models.CharField(blank=True, max_length=600, null=True, verbose_name='\u6807\u7b7e\u5185\u5bb9')),
                ('son_tag', models.ManyToManyField(related_name='_taginfo_son_tag_+', to='destination.TagInfo', verbose_name='\u5b50\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e\u4fe1\u606f',
                'verbose_name_plural': '\u6807\u7b7e\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='tagdestination',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.TagInfo', verbose_name='\u6807\u7b7e\u4fe1\u606f'),
        ),
    ]
