# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_auto_20171214_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondtaginfo',
            name='third_tag',
            field=models.ManyToManyField(blank=True, null=True, to='destination.ThirdTagInfo', verbose_name='\u4e09\u7ea7\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='taginfo',
            name='second_tag',
            field=models.ManyToManyField(blank=True, null=True, to='destination.SecondTagInfo', verbose_name='\u4e8c\u7ea7\u6807\u7b7e'),
        ),
    ]
