# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_auto_20171214_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifthTagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('type', models.IntegerField(choices=[(1, '\u901a\u7528\u6807\u7b7e'), (2, '\u7279\u8272\u6807\u7b7e')], default=1, verbose_name='\u6807\u7b7e\u7c7b\u578b')),
                ('desc', models.CharField(blank=True, max_length=600, null=True, verbose_name='\u6807\u7b7e\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u4e94\u7ea7\u6807\u7b7e\u4fe1\u606f',
                'verbose_name_plural': '\u4e94\u7ea7\u6807\u7b7e\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='FourthTagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('type', models.IntegerField(choices=[(1, '\u901a\u7528\u6807\u7b7e'), (2, '\u7279\u8272\u6807\u7b7e')], default=1, verbose_name='\u6807\u7b7e\u7c7b\u578b')),
                ('desc', models.CharField(blank=True, max_length=600, null=True, verbose_name='\u6807\u7b7e\u5185\u5bb9')),
                ('fifth_tag', models.ManyToManyField(blank=True, null=True, to='destination.FifthTagInfo', verbose_name='\u4e94\u7ea7\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u56db\u7ea7\u6807\u7b7e\u4fe1\u606f',
                'verbose_name_plural': '\u56db\u7ea7\u6807\u7b7e\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='\u56fe\u7247')),
                ('add_id', models.IntegerField(default=0, verbose_name='\u4f7f\u7528\u56fe\u7247\u5bf9\u8c61id')),
                ('image_type', models.IntegerField(choices=[(1, '\u76ee\u7684\u5730\u56fe\u7247'), (2, '\u670d\u52a1\u56fe\u7247'), (3, '\u6d3b\u52a8\u56fe\u7247')], default=1, verbose_name='\u56fe\u7247\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u56fe\u7247\u4fe1\u606f',
                'verbose_name_plural': '\u56fe\u7247\u4fe1\u606f',
            },
        ),
        migrations.RemoveField(
            model_name='destinationimage',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='\u8054\u7cfb\u4eba\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='destination',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8054\u7cfb\u4eba\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearby_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.Destination', verbose_name='\u9644\u8fd1\u7684\u76ee\u7684\u5730'),
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
        migrations.AddField(
            model_name='thirdtaginfo',
            name='fourth_tag',
            field=models.ManyToManyField(blank=True, null=True, to='destination.FourthTagInfo', verbose_name='\u56db\u7ea7\u6807\u7b7e'),
        ),
    ]
