# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-15 16:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(default=0, verbose_name='\u8bc4\u4ef7\u661f\u7ea7')),
                ('comment_type', models.IntegerField(choices=[(1, '\u76ee\u7684\u5730'), (2, '\u670d\u52a1'), (3, '\u6d3b\u52a8')], default=1, verbose_name='\u8bc4\u8bba\u7c7b\u578b')),
                ('comments', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('commented_id', models.IntegerField(default=0, verbose_name='\u88ab\u8bc4\u8bba\u6570\u636eID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8bc4\u8bba',
                'verbose_name_plural': '\u7528\u6237\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='\u88ab\u6536\u85cf\u6570\u636eid')),
                ('fav_type', models.IntegerField(choices=[(1, '\u76ee\u7684\u5730'), (2, '\u670d\u52a1'), (3, '\u6d3b\u52a8')], default=1, verbose_name='\u6536\u85cf\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_up_id', models.IntegerField(default=0, verbose_name='\u88ab\u70b9\u8d5e\u56fe\u7247id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u70b9\u8d5e',
                'verbose_name_plural': '\u7528\u6237\u70b9\u8d5e',
            },
        ),
    ]
