# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-15 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0004_auto_20171215_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6d3b\u52a8\u540d\u79f0')),
                ('desc', models.CharField(max_length=600, verbose_name='\u6d3b\u52a8\u4ecb\u7ecd')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('cost', models.CharField(max_length=100, verbose_name='\u6d3b\u52a8\u8d39\u7528')),
                ('start_time', models.DateTimeField(default='', verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(default='', verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('destination', models.ManyToManyField(to='destination.Destination', verbose_name='\u6d3b\u52a8\u76ee\u7684\u5730')),
                ('tag', models.ManyToManyField(to='destination.TagInfo', verbose_name='\u6807\u7b7e\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8\u4fe1\u606f',
                'verbose_name_plural': '\u6d3b\u52a8\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('desc', models.CharField(max_length=600, verbose_name='\u670d\u52a1\u4ecb\u7ecd')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('cost', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u8d39\u7528')),
                ('start_time', models.DateTimeField(default='', verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(default='', verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('destination', models.ManyToManyField(to='destination.Destination', verbose_name='\u670d\u52a1\u76ee\u7684\u5730')),
                ('tag', models.ManyToManyField(to='destination.TagInfo', verbose_name='\u6807\u7b7e\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u4fe1\u606f',
            },
        ),
    ]
